In [92]:
import pandas as pd

In [93]:
pd.set_option("display.max_columns", None)

In [94]:
from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root:9095@localhost/rapido")

## import data from SQL

In [95]:
query = """select 
day_of_week, city, vehicle_type, 
ride_distance_km, estimated_ride_time_min, traffic_level, 
weather_condition, base_fare, surge_multiplier 
from bookings
where booking_status = 'Completed'"""
X = pd.read_sql(query, engine, None)
X

,day_of_week,city,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier
0,Monday,Mumbai,Cab,9.67,43.54,Medium,Heavy Rain,254.15,1.8
1,Saturday,Delhi,Bike,1.02,4.61,Medium,Rain,28.20,1.8
2,Saturday,Hyderabad,Bike,12.35,55.56,Medium,Clear,118.77,1.2
3,Saturday,Mumbai,Bike,22.46,101.08,Medium,Clear,199.70,1.5
4,Sunday,Delhi,Auto,10.31,68.04,High,Clear,163.72,1.4
...,...,...,...,...,...,...,...,...,...
68341,Sunday,Chennai,Auto,12.32,55.42,Medium,Rain,187.79,1.5
68342,Monday,Mumbai,Auto,9.58,63.25,High,Rain,155.00,2.0
68343,Wednesday,Bangalore,Auto,7.57,34.06,Medium,Heavy Rain,130.84,1.8
68344,Wednesday,Hyderabad,Cab,22.87,150.95,High,Clear,491.68,1.4
68345,Friday,Bangalore,Cab,15.76,70.94,Medium,Rain,363.74,1.5

In [96]:
query1 = "select booking_value from bookings where booking_status = 'Completed'"
y = pd.read_sql(query1, engine, None)
y

       booking_value
0             465.85
1              51.03
2             144.73
3             296.65
4             226.01
...              ...
68341         292.05
68342         300.66
68343         241.33
68344         662.67
68345         522.25

[68346 rows x 1 columns]

## train test split:

In [97]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
len(X_train)

54676

In [98]:
X_train

,day_of_week,city,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier
816,Thursday,Mumbai,Cab,15.98,71.90,Medium,Rain,367.59,1.5
43777,Sunday,Chennai,Bike,3.86,11.59,Low,Heavy Rain,50.92,1.9
20585,Thursday,Chennai,Bike,4.99,32.93,High,Heavy Rain,59.91,2.3
46396,Friday,Chennai,Cab,19.60,129.34,High,Heavy Rain,432.74,2.3
54965,Friday,Hyderabad,Cab,19.56,88.02,Medium,Rain,432.07,1.5
...,...,...,...,...,...,...,...,...,...
37194,Tuesday,Hyderabad,Bike,14.23,93.91,High,Rain,133.83,1.7
6265,Monday,Mumbai,Auto,24.59,73.77,Low,Clear,335.07,1.0
54886,Sunday,Chennai,Auto,4.33,19.47,Medium,Heavy Rain,91.92,2.1
860,Monday,Bangalore,Bike,21.87,65.62,Low,Rain,194.99,1.3
15795,Friday,Delhi,Auto,6.51,29.28,Medium,Rain,118.07,1.5

In [99]:
X_test.columns

Index(['day_of_week', 'city', 'vehicle_type', 'ride_distance_km',
       'estimated_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier'],
      dtype='object')

In [100]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54676 entries, 816 to 15795
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   day_of_week              54676 non-null  object
 1   city                     54676 non-null  object
 2   vehicle_type             54676 non-null  object
 3   ride_distance_km         54676 non-null  float64
 4   estimated_ride_time_min  54676 non-null  float64
 5   traffic_level            54676 non-null  object
 6   weather_condition        54676 non-null  object
 7   base_fare                54676 non-null  float64
 8   surge_multiplier         54676 non-null  float64
dtypes: float64(4), object(5)
memory usage: 4.2+ MB

In [101]:
y_train

       booking_value
816           574.18
43777         101.36
20585         139.92
46396         969.40
54965         672.11
...              ...
37194         227.82
6265          333.47
54886         188.67
860           242.33
15795         171.43

[54676 rows x 1 columns]

## PreProcessing Train data:

## Encoding Categorical features

In [102]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse_output = False)
X_train_ohe_array = OHE.fit_transform(X_train[["day_of_week", "city", "vehicle_type", "traffic_level", "weather_condition"]])
X_train_ohe_array

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(54676, 21))

In [103]:
X_train_encoded = pd.DataFrame(X_train_ohe_array, columns = OHE.get_feature_names_out(), index = X_train.index)
X_train_encoded

,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,traffic_level_High,traffic_level_Low,traffic_level_Medium,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain
816,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
43777,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20585,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
46396,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
54965,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37194,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6265,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
54886,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
860,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
15795,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [104]:
X_train_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54676 entries, 816 to 15795
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   day_of_week_Friday            54676 non-null  float64
 1   day_of_week_Monday            54676 non-null  float64
 2   day_of_week_Saturday          54676 non-null  float64
 3   day_of_week_Sunday            54676 non-null  float64
 4   day_of_week_Thursday          54676 non-null  float64
 5   day_of_week_Tuesday           54676 non-null  float64
 6   day_of_week_Wednesday         54676 non-null  float64
 7   city_Bangalore                54676 non-null  float64
 8   city_Chennai                  54676 non-null  float64
 9   city_Delhi                    54676 non-null  float64
 10  city_Hyderabad                54676 non-null  float64
 11  city_Mumbai                   54676 non-null  float64
 12  vehicle_type_Auto             54676 non-null  float64
 13  vehicle_type_Bike             54676 non-null  float64
 14  vehicle_type_Cab              54676 non-null  float64
 15  traffic_level_High            54676 non-null  float64
 16  traffic_level_Low             54676 non-null  float64
 17  traffic_level_Medium          54676 non-null  float64
 18  weather_condition_Clear       54676 non-null  float64
 19  weather_condition_Heavy Rain  54676 non-null  float64
 20  weather_condition_Rain        54676 non-null  float64
dtypes: float64(21)
memory usage: 9.2 MB

## Scaling Numerical features:

In [105]:
from sklearn.preprocessing import MinMaxScaler
cols = ["ride_distance_km", "estimated_ride_time_min", "base_fare", "surge_multiplier"]
MMS = MinMaxScaler()
X_train_scaled = pd.DataFrame(MMS.fit_transform(X_train[cols]), columns = cols, index = X_train.index)
X_train_scaled

       ride_distance_km  estimated_ride_time_min  base_fare  surge_multiplier
816            0.624167                 0.425387   0.676542          0.384615
43777          0.119167                 0.053035   0.045625          0.692308
20585          0.166250                 0.184787   0.063536          1.000000
46396          0.775000                 0.780021   0.806344          1.000000
54965          0.773333                 0.524912   0.805009          0.384615
...                 ...                      ...        ...               ...
37194          0.551250                 0.561277   0.210810          0.538462
6265           0.982917                 0.436933   0.611751          0.000000
54886          0.138750                 0.101685   0.127311          0.846154
860            0.869583                 0.386615   0.332663          0.230769
15795          0.229583                 0.162252   0.179411          0.384615

[54676 rows x 4 columns]

## Concatinate encoded and scaled dataframes together:

In [106]:
X_train_final = pd.concat([X_train_scaled, X_train_encoded], axis = 1)
X_train_final

,ride_distance_km,estimated_ride_time_min,base_fare,surge_multiplier,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,traffic_level_High,traffic_level_Low,traffic_level_Medium,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain
816,0.624167,0.425387,0.676542,0.384615,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
43777,0.119167,0.053035,0.045625,0.692308,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20585,0.166250,0.184787,0.063536,1.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
46396,0.775000,0.780021,0.806344,1.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
54965,0.773333,0.524912,0.805009,0.384615,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37194,0.551250,0.561277,0.210810,0.538462,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6265,0.982917,0.436933,0.611751,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
54886,0.138750,0.101685,0.127311,0.846154,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
860,0.869583,0.386615,0.332663,0.230769,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
15795,0.229583,0.162252,0.179411,0.384615,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [107]:
X_train_final.isnull().sum()

ride_distance_km                0
estimated_ride_time_min         0
base_fare                       0
surge_multiplier                0
day_of_week_Friday              0
day_of_week_Monday              0
day_of_week_Saturday            0
day_of_week_Sunday              0
day_of_week_Thursday            0
day_of_week_Tuesday             0
day_of_week_Wednesday           0
city_Bangalore                  0
city_Chennai                    0
city_Delhi                      0
city_Hyderabad                  0
city_Mumbai                     0
vehicle_type_Auto               0
vehicle_type_Bike               0
vehicle_type_Cab                0
traffic_level_High              0
traffic_level_Low               0
traffic_level_Medium            0
weather_condition_Clear         0
weather_condition_Heavy Rain    0
weather_condition_Rain          0
dtype: int64

## Scaling Target feature:

#### Not scaling the target feature, keeping with original fares for easy interpretation and to avoid unwanted transform and inverse transform

## Preprocessing Test data:

In [108]:
X_test

,day_of_week,city,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier
46243,Tuesday,Delhi,Cab,6.15,18.46,Low,Heavy Rain,190.77,1.6
50495,Saturday,Hyderabad,Auto,21.85,98.31,Medium,Rain,302.15,1.8
63055,Sunday,Chennai,Cab,12.66,56.98,Medium,Clear,307.91,1.2
40361,Saturday,Delhi,Bike,11.01,72.68,High,Clear,108.10,1.4
16039,Sunday,Chennai,Cab,9.32,27.95,Low,Clear,247.71,1.0
...,...,...,...,...,...,...,...,...,...
23309,Sunday,Delhi,Auto,18.90,85.07,Medium,Clear,266.84,1.2
32729,Friday,Chennai,Cab,8.91,58.82,High,Rain,240.41,2.0
6188,Monday,Chennai,Bike,13.68,90.30,High,Rain,129.45,1.7
63284,Sunday,Hyderabad,Auto,24.12,108.55,Medium,Heavy Rain,329.46,1.8
44734,Wednesday,Delhi,Cab,9.22,60.85,High,Clear,245.96,1.4

In [109]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13670 entries, 46243 to 44734
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   day_of_week              13670 non-null  object
 1   city                     13670 non-null  object
 2   vehicle_type             13670 non-null  object
 3   ride_distance_km         13670 non-null  float64
 4   estimated_ride_time_min  13670 non-null  float64
 5   traffic_level            13670 non-null  object
 6   weather_condition        13670 non-null  object
 7   base_fare                13670 non-null  float64
 8   surge_multiplier         13670 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.0+ MB

In [110]:
y_test

       booking_value
46243         309.23
50495         532.21
63055         354.64
40361         147.05
16039         254.20
...              ...
23309         324.02
32729         466.44
6188          215.05
63284         589.26
44734         346.00

[13670 rows x 1 columns]

## Encoding Categorical features

In [111]:
X_test_ohe_array = OHE.transform(X_test[["day_of_week", "city", "vehicle_type", "traffic_level", "weather_condition"]])
X_test_encoded = pd.DataFrame(X_test_ohe_array, columns = OHE.get_feature_names_out(), index = X_test.index)
X_test_encoded.isnull().sum()

day_of_week_Friday              0
day_of_week_Monday              0
day_of_week_Saturday            0
day_of_week_Sunday              0
day_of_week_Thursday            0
day_of_week_Tuesday             0
day_of_week_Wednesday           0
city_Bangalore                  0
city_Chennai                    0
city_Delhi                      0
city_Hyderabad                  0
city_Mumbai                     0
vehicle_type_Auto               0
vehicle_type_Bike               0
vehicle_type_Cab                0
traffic_level_High              0
traffic_level_Low               0
traffic_level_Medium            0
weather_condition_Clear         0
weather_condition_Heavy Rain    0
weather_condition_Rain          0
dtype: int64

## Scaling Numerical features:

In [112]:
X_test_scaled = pd.DataFrame(MMS.transform(X_test[cols]), columns = cols, index = X_test.index)
X_test_scaled.isnull().sum()

ride_distance_km           0
estimated_ride_time_min    0
base_fare                  0
surge_multiplier           0
dtype: int64

## Concatinate encoded and scaled dataframes together:

In [113]:
X_test_final = pd.concat([X_test_scaled, X_test_encoded], axis = 1)
X_test_final

,ride_distance_km,estimated_ride_time_min,base_fare,surge_multiplier,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,traffic_level_High,traffic_level_Low,traffic_level_Medium,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain
46243,0.214583,0.095450,0.324255,0.461538,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
50495,0.868750,0.588442,0.546163,0.615385,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
63055,0.485833,0.333272,0.557639,0.153846,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
40361,0.417083,0.430203,0.159547,0.307692,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
16039,0.346667,0.154041,0.437699,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23309,0.745833,0.506699,0.475813,0.153846,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
32729,0.329583,0.344632,0.423155,0.769231,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
6188,0.528333,0.538989,0.202084,0.538462,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
63284,0.963333,0.651664,0.600574,0.615385,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
44734,0.342500,0.357165,0.434213,0.307692,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0

## Scaling Target feature:

#### Not scaling the target feature, keeping with original fares for easy interpretation and to avoid unwanted transform and inverse transform

In [114]:
# import matplotlib.pyplot as plt
# plt.boxplot(X[cols])
# plt.boxplot(X_train[cols])
# plt.boxplot(X_train_scaled[cols])
# plt.boxplot(X_test[cols])
# plt.boxplot(X_test_scaled[cols])

## Model training:

In [115]:
from sklearn.linear_model import SGDRegressor

In [116]:
fare_sgd = SGDRegressor(random_state = 42)
fare_sgd.fit(X_train_final, y_train.values.ravel())

SGDRegressor(random_state=42)

In [117]:
import joblib
fare_predction_model = joblib.dump(fare_sgd, "fare_sgd.pkl")

In [118]:
y_pred = pd.DataFrame(fare_sgd.predict(X_test_final), columns = y_test.columns, index = X_test_final.index)
y_pred

       booking_value
46243     323.386818
50495     518.810967
63055     401.043087
40361     132.028147
16039     276.294182
...              ...
23309     339.154129
32729     456.722771
6188      235.762555
63284     561.781314
44734     340.377626

[13670 rows x 1 columns]

In [119]:
y_test

       booking_value
46243         309.23
50495         532.21
63055         354.64
40361         147.05
16039         254.20
...              ...
23309         324.02
32729         466.44
6188          215.05
63284         589.26
44734         346.00

[13670 rows x 1 columns]

In [120]:
fare_sgd.score(X_test_final, y_test)

0.9644267849797181

In [121]:
fare_sgd.score(X_train_final, y_train)

0.9641079419385371

In [122]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [123]:
mean_absolute_error(y_pred, y_test)

27.067338231875212

In [124]:
mean_squared_error(y_pred, y_test)

1427.0877218396188

In [125]:
from sklearn.linear_model import LinearRegression
fare_linreg = LinearRegression()
fare_linreg.fit(X_train_final,  y_train.values.ravel())

LinearRegression()

In [126]:
import joblib
fare_predction_model = joblib.dump(fare_linreg, "fare_linreg.pkl")

In [127]:
fare_linreg.score(X_test_final, y_test)

0.964567798488459

In [128]:
fare_linreg.score(X_train_final, y_train)

0.9642024290825724

In [129]:
lr_y_pred = pd.DataFrame(fare_linreg.predict(X_test_final))
lr_y_pred

                0
0      321.678021
1      518.343387
2      400.331290
3      132.334914
4      275.225999
...           ...
13665  338.348827
13666  455.296790
13667  235.829259
13668  560.604003
13669  338.297786

[13670 rows x 1 columns]

In [130]:
mean_absolute_error(lr_y_pred, y_test)

27.083983196305912

In [131]:
mean_squared_error(lr_y_pred, y_test)

1421.4306945840601

In [132]:
import numpy as np

# 1. Calculate the percentage error for every single ride
percentage_errors = np.abs(y_test - lr_y_pred) / y_test

# 2. Calculate the Median Absolute Percentage Error
mdape = np.median(percentage_errors) * 100

print(f"Typical Prediction Error: {mdape:.2f}%")

# 3. Validation Check
if mdape <= 10:
    print("🟢 Criteria Met: Typical error is within ±10% of the actual fare!")
else:
    print("🔴 Criteria Failed: Typical error exceeds ±10%.")

Typical Prediction Error: nan%
🔴 Criteria Failed: Typical error exceeds ±10%.